### ISSUE TITLE
[Bug]: Unexpected behavior with cw command

### ISSUE THREAD

**Issue by Seth-Buchanan** [chrisgrieser/nvim-spider#10]
### Bug Description

I found and issue with the cw command. The default vim behavior when entering cw on a word in sentence is to preserve the post space which allows you to type a word and not have to add a space. This is in contrast to the dw command that deletes the post word space to make that word seem like it was never there. 

Another unexpected behavior is that pressing cw on the last word in the line deletes the newline character as well. This makes the next line append to what is left of the current line.

ciw does work as expected and is recommended to use over cw but I thought I would raise it to your attention.

### To Reproduce

Type text, go to the begining of  a word, and use the cw command. Type multiple lines and use cw command on any line but the last.

### neovim version

```Text
0.8.3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
> The default vim behavior when entering cw on a word in sentence is to preserve the post space which allows you to type a word and not have to add a space. This is in contrast to the dw command that deletes the post word space to make that word seem like it was never there.

Yeah, vim's original `web` motions work quite inconsistent in this regard. I deliberately not implemented the same for this plugin, since with subword motions and punctuation skipping, you get a lot of other unexpected before if you introduce vim's behavior here. Same thing for `dw` and `cw` not working at the end of a file: When you are at the last word of a file, there literally is not next word, so not doing anything is actually the intended behavior. 

In my view, original vim actually taught many people a bad habit here of treating `cw` differently, when people should actually be using `ce` instead. If you really want to, you can map `cw` to `ce` though, which should get you your desired behavior.

I added some info on this to the docs though.

> ciw does work as expected 

that's cause this plugin does not change the `iw` text object at all ;)
