### ISSUE TITLE
Feature Request: Add option to use default keymaps 

### ISSUE THREAD

**Issue by kevintraver** [chrisgrieser/nvim-spider#27]
### Feature Requested

Would be nice to just use the default keymaps if we like them, therefore reducing the need to explicitly adding the keymaps in config.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I have thought about that, too, but the problem with that is that some people like to overwrite the default `w`, `e`, `b` motions, while others like to use them as alternative movements, e.g. `<leader>w`, `<leader>e`, `<leader>b`, or even `gw`, `ge`, `gb`

So there are no good "defaults" I could go for. But since it literally is only 4 lines of code you can copypaste from the repo, I don't think it's a big deal to let the user set their own keymaps.

**Comment by kevintraver** [comment]
That makes sense. Thanks for the response
