### ISSUE TITLE
[Bug]: Jumps are too large with `c`, `d`, `y` ... modifiers

### ISSUE THREAD

**Issue by jgollenz** [chrisgrieser/nvim-spider#3]
### Bug Description

Disclaimer: I'm not sure if this is a bug or expected behavior, but at least for me it's not the behavior I would expect.

Consider this sentence:
```
I do like nvim-spider
     ^
```

From here, `dw` will delete `like n` and not just `like` as I would expect in plain nvim. One (not me) might argue that this is actually what _should_ happen in nvim as well, since `vw` will highlight `like n`. I am aware that I can achieve my intention with `de`, but since it's not what I would do in nvim, it feels a bit off. I guess I don't see the utility of deleting up to the first letter of the next word. Maybe that's why nvim doesn't do it either?

### neovim version

```Text
0.8.3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by devinalvaro** [comment]
`db` in this case will only delete `o ` too, while normal `db` will delete `do `.

**Comment by xiyaowong** [comment]
```lua
vim.keymap.set({"n"}, "w", function() require("spider").motion("w") end, { desc = "Spider-w" })
vim.keymap.set({"n"}, "e", function() require("spider").motion("e") end, { desc = "Spider-e" })
vim.keymap.set({"n"}, "b", function() require("spider").motion("b") end, { desc = "Spider-b" })
vim.keymap.set({"n"}, "ge", function() require("spider").motion("ge") end, { desc = "Spider-ge" })
```
Only use `spider` in normal mode

**Comment by jgollenz** [comment]
> Only use `spider` in normal mode

I want to use spider in the other modes as well though ;) 
```
I do like nvim-spider
          ^
```
when I'm here I want `w` to jump to the beginning of `spider` and `dw` delete either `nvim` or `nvim-` but not `nvim-spider`.

**Comment by chrisgrieser** [comment]
ah, good call. Fixed in latest release

**Comment by mcmillion** [comment]
> Only use spider in normal mode

This happens in normal mode.

**Comment by chrisgrieser** [comment]
@fakeharxy I think in that case, it works as expected. `w` goes to the beginning of the next word, and in operator pending deletes up to that. If you want to preserve the `)`, you should use `e`, since it only deletes to the end of the word.

Both is also consistent with what happens with the original `e` and `w` motions from vim.

**Comment by tobiaslieber** [comment]
> Hello, not sure what the etiquette is for commenting on closed issues, but I'm not sure this is fixed yet, or at least, it doesn't work as expected for me with brackets:
> 
> `word) is`
> 
> cursor on w of word. Press `dw` or `cw` and you get:
> 
> ` is`

@fakeharxy I stumbled over the same issue. I was confused since this deviates from the default behaviour of (n)vim for `dw` and `cw`.

```
require("spider").setup({
	skipInsignificantPunctuation = false
})
```
does the trick for `cw` and `dw`, while the "normal" movement behaves differently then.

@chrisgrieser Probably it makes sense to have the `skipInsignificantPunctuation` option on the motion function (and not (just) as a global configuration value). Then it would be possible to have different motion behavior on the modes `n`, `o`, and `x`.

**Comment by chrisgrieser** [comment]
Could one of you open a new issue and properly outline expected and actual behavior? Then I can look into it
