### ISSUE TITLE
[Bug]: Cannot bind to e.g. "<leader>w"

### ISSUE THREAD

**Issue by Mithrandir2k18** [chrisgrieser/nvim-spider#32]
### Bug Description

In vim I am using CamelCaseMotion and bind those to e.g. "<leader>w" when I want camelcase motion and leave w as it is by default. This also works with delete/change, so when my Cursor is at the start of "CamelCase" and I want to change it to "PascalCase" I can do "c<space>wPascal<Esc>" to do that. However when I try this in neovim either with CamelCaseMotion.vim or your plugin, when I type "c<space>" it basically does the same thing as "s", it deletes the character I am on and puts me into insert mode right away.

### Reproduction & Sample Text

before: CamelCase
----------^--------------
after: PascalamelCase
expected: PascalCase

### neovim version

```Text
v0.10.0-dev
```

### Make sure you have done the following

- [X] In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
> However when I try this in neovim either with CamelCaseMotion.vim or your plugin, when I type "c" it basically does the same thing as "s", it deletes the character I am on and puts me into insert mode right away.

Well, that appears to be an issue with your nvim config? Sounds like you either have something mapped to `c` in your config, or some other plugin interfering. Either way, that does not appear to be related to this plugin.

I'd ask in a more general forum, e.g. the nvim subreddit or discourse about it, since this is only for issues related specifically caused by this plugin.

**Comment by Mithrandir2k18** [comment]
kk, will do
