### ISSUE TITLE
[Bug]: numbers in hex values are not ignored

### ISSUE THREAD

**Issue by leg7** [chrisgrieser/nvim-spider#33]
### Bug Description

Hey it's me again.

since the fix for bug #31 now motions in hex colors stop at numbers:

I would expect motions to ignore this gibberish but maybe it would be to hard to implement the skip efficently? I know vim knows how to recognize hex values natively because `<C-x>` and `<C-a>` can decrement and increment these respectively.

### Reproduction & Sample Text

Code to try it out:
```
$selection  = 	 eceff4
$background = 	 2e3440
$red        = 	 EF5350
$green      = 	 66BB6A
$yellow     = 	 E2C12F
$blue       = 	 42A5F5
$mageta     = 	 AB47BC
$cyan       = 	 26C6DA
$foreground = 	 D8DEE9
```

### neovim version

```Text
0.9.4
```

### Make sure you have done the following

- [X] In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Well, fixing it is not the issue. The issue is rather deciding how exactly the nvim-spider is supposed to behave. Ignoring things that look like hex values is very problematic, since there are a lot of ambiguous cases. For example, is `123456` a hex value or a number? Is `face01` a hex value or a variable name? And what about other things like hashes?

Like, there are really a lot of edge cases here. When in doubt, I'd prefer to go with the straightforward solution (nvim-spider goes by subwords/digits, regardless of whether they might be hashes/hex codes etc.), since that even though not perfect, it's easy to remember how the plugin will behave. Adding ambiguous edge cases how the plugin should behave are a problem, since users with variables like `face01` will be enormously confused why nvim-spider behaves differently here than with `back01`.

I think the current implemention of nvim-spider with the change suggested in #31 makes most sense, and I think I'd prefer it over adding ambiguity via things like hex codes. I'd be open for suggestions though if you can provide a detailed and unambiguous specification how exactly nvim-spider should treat numbers.

**Comment by chrisgrieser** [comment]
You might be interested in the custom-pattern feature I recently added, which allows you to define a set of patterns defining stopping points yourself: https://github.com/chrisgrieser/nvim-spider/blob/main/README.md#advanced-custom-movement-patterns

**Comment by gokberkgunes** [comment]
I am facing this issue as well. I have hex codes that start with `#` such as `#e1f0aa`, and nvim-spider thinks this is a camel case. Right now, these words nvim-spider thinks camel case appears as  false positives.

At worst condition, I believe nvim-spider should avoid strings starting with `#` as camel case. Moreover, a setting that would consider a word with numbers as a whole word could be implemented.

**Comment by chrisgrieser** [comment]
@gokberkgunes you can achieve all that with custom movement patterns. See the readme.
