### ISSUE TITLE
[Question] Why ignore iskeyword?

### ISSUE THREAD

**Issue by gbroques** [chrisgrieser/nvim-spider#41]
[The README mentions](https://github.com/chrisgrieser/nvim-spider/blob/828444de406bc7df3b30c8e000ce6f54f0754499/README.md?plain=1#L80-L81):

> ℹ️ This plugin ignores vim's `iskeyword` option.

Can you elaborate on why a user would choose this plugin over setting the `iskeyword` option, and why this plugin doesn't use that internally?

Is it possible to achieve similar behavior using the built-in `iskeyword` option?

Thank you for your work on these various plugins! :)

**Comment by chrisgrieser** [comment]
`iskeyword` defines what characters count as part of a word. If you just want to treat hyphens as weird characters, e.g. for  CSS, that's completely suffice. 

However, subword motions as well as the skipping of insignificant punctuation cannot be achieved with that setting, which is why I created this plugin. 

The plugin simply does not use the iskeyword-setting, since it wild complicate the user configuration as well as the internal working of the plugin to consider a vim setting and plugin settings at the same time. Any behavior you can achieve with iskeyword, you can also achieve with this plugin's advanced config.

**Comment by gbroques** [comment]
> `iskeyword` defines what characters count as part of a word. If for instance you just want to treat hyphens as word characters, e.g. for CSS, that completely suffices.
> 
> However, subword motions as well as the skipping of insignificant punctuation cannot be achieved with that setting, which is why I created this plugin.
> 
> The plugin simply does not use the iskeyword-setting, since it would overcomplicate the user configuration as well as the internal working of this plugin to consider a vim setting and plugin settings at the same time. Any behavior you can achieve with iskeyword, you can also achieve with this plugin's advanced config.

Thanks for the clarifcations & reply @chrisgrieser!
