### ISSUE TITLE
Feature Request: Add support for `c`, `d`, and other verbs

### ISSUE THREAD

**Issue by ispringle** [chrisgrieser/nvim-spider#9]
### Feature Requested

I'm not sure if this is a bug or a feature request, but wanted to err on the side of caution.

When using this plugin to navigate it works as expected. However, when this plugin is enabled, the keybindings are set, and it's set to skip insignificant punctuation it breaks things like `cw` because it will clear the word and _all_ trailing insignificant punctuation. For example, if I have the string `require('ThisCamelCaseFile').setup({...})` and my cursor is on the `F` in `File` and I type `cw` what I expect is that it would clear out `File` and leave me in insert mode after the `e` in `Case` and before the trailing `'`. Instead it's clearing out `File').` and leaving me in insert mode after the `e` in `Case` and before the `s` in `setup`.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Yes, that is pretty much the intended behavior – when used as verb, the commands work on the range that would otherwise be passed over when they were used as motion. 

I also refrain from changing this behavior, since this to my knowledge, is pretty much the standard how motions behave in vim in general.

For your specific case, you should actually use the `e` key: with `cw`, it file delete "File" and enter insert mode as you intended.
